name: objects
description: A sample command-line application.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.5.4

dependencies:
  controller:
    path: ../controller
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
