name: controller
description: A sample command-line application.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
